// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexaLearn.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexaLearn.Infrastructure.Migrations
{
    [DbContext(typeof(NexaLearnDbContext))]
    partial class NexaLearnDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("courses", (string)null);
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Duration")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("module_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("module_id");

                    b.ToTable("lessons", (string)null);
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("course_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("course_id");

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Enrollments.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("EnrolledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enrolled_at");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<List<Guid>>("_completedLessonIds")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("completed_lesson_ids");

                    b.HasKey("Id");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_student_course");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Students.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_students_email");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Course", b =>
                {
                    b.OwnsOne("NexaLearn.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("price");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("currency");

                            b1.HasKey("CourseId");

                            b1.ToTable("courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Lesson", b =>
                {
                    b.HasOne("NexaLearn.Domain.Aggregates.Courses.Module", null)
                        .WithMany("Lessons")
                        .HasForeignKey("module_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Module", b =>
                {
                    b.HasOne("NexaLearn.Domain.Aggregates.Courses.Course", null)
                        .WithMany("Modules")
                        .HasForeignKey("course_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Course", b =>
                {
                    b.Navigation("Modules");
                });

            modelBuilder.Entity("NexaLearn.Domain.Aggregates.Courses.Module", b =>
                {
                    b.Navigation("Lessons");
                });
#pragma warning restore 612, 618
        }
    }
}
